/* htaccess-gen.js
   Pure browser JS — no external requests, no API keys.
   Generates Apache .htaccess file content from form inputs.
*/
"use strict";

// ── State: current output lines ───────────────────────────────────────────────
let outputLines = [
    "# .htaccess — generated by htaccess Generator",
    "# https://independent-utilities/tools/other-tools/htaccess-gen/",
    "",
    "Options -Indexes",
    "RewriteEngine On",
    "",
];

// ── Common patterns ───────────────────────────────────────────────────────────
const PATTERNS = [
    {
        id: "https",
        label: "Force HTTPS",
        desc: "Redirect all HTTP traffic to HTTPS",
        code: [
            "# Force HTTPS",
            "RewriteCond %{HTTPS} off",
            "RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]",
        ],
    },
    {
        id: "www",
        label: "Force www",
        desc: "Redirect non-www to www.example.com",
        code: [
            "# Force www",
            "RewriteCond %{HTTP_HOST} !^www\\. [NC]",
            "RewriteRule ^ https://www.%{HTTP_HOST}%{REQUEST_URI} [L,R=301]",
        ],
    },
    {
        id: "nowww",
        label: "Remove www",
        desc: "Redirect www.example.com to example.com",
        code: [
            "# Remove www",
            "RewriteCond %{HTTP_HOST} ^www\\.(.+)$ [NC]",
            "RewriteRule ^ https://%1%{REQUEST_URI} [L,R=301]",
        ],
    },
    {
        id: "nohtml",
        label: "Remove .html extension",
        desc: "Serve /page instead of /page.html",
        code: [
            "# Remove .html extension",
            "RewriteCond %{REQUEST_FILENAME} !-d",
            "RewriteCond %{REQUEST_FILENAME}\\.html -f",
            "RewriteRule ^([^.]+)$ $1.html [L]",
        ],
    },
    {
        id: "trailingslash",
        label: "Add trailing slash",
        desc: "Redirect /page to /page/ for directories",
        code: [
            "# Add trailing slash to directories",
            "RewriteCond %{REQUEST_FILENAME} -d",
            "RewriteCond %{REQUEST_URI} !/$",
            "RewriteRule ^ %{REQUEST_URI}/ [L,R=301]",
        ],
    },
    {
        id: "nodir",
        label: "Disable directory listing",
        desc: "Return 403 instead of showing directory contents",
        code: [
            "# Disable directory listing",
            "Options -Indexes",
        ],
    },
    {
        id: "custom404",
        label: "Custom 404 page",
        desc: "Serve a custom error page for 404 Not Found",
        code: [
            "# Custom 404 error page",
            "ErrorDocument 404 /404.html",
        ],
    },
    {
        id: "nohotlink",
        label: "Block image hotlinking",
        desc: "Prevent other sites from embedding your images",
        code: [
            "# Block image hotlinking",
            "RewriteCond %{HTTP_REFERER} !^$",
            "RewriteCond %{HTTP_REFERER} !^https?://(www\\.)?yourdomain\\.com/ [NC]",
            "RewriteRule \\.(gif|jpg|jpeg|png|webp|svg)$ - [F,NC]",
        ],
    },
    {
        id: "phpphp",
        label: "Remove .php extension",
        desc: "Serve /page instead of /page.php",
        code: [
            "# Remove .php extension",
            "RewriteCond %{REQUEST_FILENAME} !-d",
            "RewriteCond %{REQUEST_FILENAME}\\.php -f",
            "RewriteRule ^([^.]+)$ $1.php [L]",
        ],
    },
    {
        id: "secheaders",
        label: "Basic security headers",
        desc: "Add X-Frame-Options, X-Content-Type-Options, Referrer-Policy",
        code: [
            "# Security headers",
            "<IfModule mod_headers.c>",
            "    Header always set X-Frame-Options \"SAMEORIGIN\"",
            "    Header always set X-Content-Type-Options \"nosniff\"",
            "    Header always set Referrer-Policy \"strict-origin-when-cross-origin\"",
            "    Header always set X-XSS-Protection \"1; mode=block\"",
            "</IfModule>",
        ],
    },
];

// ── Render patterns grid ──────────────────────────────────────────────────────
function renderPatterns() {
    const grid = document.getElementById("patternsGrid");
    const items = PATTERNS.map(p => `
        <div class="ht-pattern-item">
            <input type="checkbox" id="pat_${p.id}" value="${p.id}">
            <label for="pat_${p.id}">
                ${escHtml(p.label)}
                <span class="ht-pattern-desc">${escHtml(p.desc)}</span>
            </label>
        </div>`).join("");

    grid.innerHTML = items + `
        <div style="grid-column:1/-1; margin-top:0.3rem">
            <button class="tool-button ht-add-btn ht-add-patterns-btn" id="addPatternsBtn">Add Selected Patterns</button>
        </div>`;

    document.getElementById("addPatternsBtn").addEventListener("click", addPatterns);
}

// ── Render output ─────────────────────────────────────────────────────────────
function renderOutput() {
    document.getElementById("htOutput").textContent = outputLines.join("\n");
}

// ── Append lines to output ────────────────────────────────────────────────────
function appendLines(newLines) {
    // Ensure one blank line separator
    if (outputLines.length > 0 && outputLines[outputLines.length - 1] !== "") {
        outputLines.push("");
    }
    outputLines.push(...newLines);
    renderOutput();
}

// ── Add single redirect ───────────────────────────────────────────────────────
function addRedirect() {
    const from = document.getElementById("rFromPath").value.trim();
    const to   = document.getElementById("rToPath").value.trim();
    const type = document.getElementById("rType").value;

    if (!from || !to) return;

    // Use Redirect for absolute URLs, RewriteRule for path-to-path with rewrite
    const isAbsolute = to.startsWith("http://") || to.startsWith("https://");
    const lines = [`# Redirect ${from} → ${to}`];

    if (isAbsolute || type === "301" || type === "302") {
        lines.push(`Redirect ${type} ${from} ${to}`);
    } else {
        lines.push(`Redirect ${type} ${from} ${to}`);
    }

    appendLines(lines);
    document.getElementById("rFromPath").value = "";
    document.getElementById("rToPath").value = "";
}

// ── Add bulk redirects ────────────────────────────────────────────────────────
function addBulkRedirects() {
    const raw = document.getElementById("bulkInput").value.trim();
    if (!raw) return;

    const lines = ["# Bulk redirects"];
    raw.split("\n").forEach(line => {
        const trimmed = line.trim();
        if (!trimmed || trimmed.startsWith("#")) return;
        const parts = trimmed.split(/\s+/);
        if (parts.length < 2) return;
        const from = parts[0];
        const to   = parts[1];
        const code = parts[2] && /^\d{3}$/.test(parts[2]) ? parts[2] : "301";
        lines.push(`Redirect ${code} ${from} ${to}`);
    });

    if (lines.length > 1) appendLines(lines);
    document.getElementById("bulkInput").value = "";
}

// ── Add selected patterns ─────────────────────────────────────────────────────
function addPatterns() {
    const checked = document.querySelectorAll(".ht-pattern-item input:checked");
    if (checked.length === 0) return;

    checked.forEach(cb => {
        const pattern = PATTERNS.find(p => p.id === cb.value);
        if (pattern) appendLines(pattern.code);
        cb.checked = false;
    });
}

// ── Copy button ───────────────────────────────────────────────────────────────
document.getElementById("copyBtn").addEventListener("click", () => {
    const text = document.getElementById("htOutput").textContent;
    navigator.clipboard.writeText(text).then(() => {
        const btn = document.getElementById("copyBtn");
        btn.textContent = "Copied!";
        btn.classList.add("copied");
        setTimeout(() => { btn.textContent = "Copy"; btn.classList.remove("copied"); }, 1800);
    });
});

// ── Clear output ──────────────────────────────────────────────────────────────
document.getElementById("clearOutputBtn").addEventListener("click", () => {
    outputLines = [
        "# .htaccess — generated by htaccess Generator",
        "",
        "Options -Indexes",
        "RewriteEngine On",
        "",
    ];
    renderOutput();
});

// ── Guide toggle ──────────────────────────────────────────────────────────────
document.getElementById("htGuideToggle").addEventListener("click", () => {
    document.getElementById("htGuideBody").classList.toggle("open");
    document.querySelector(".ht-guide-arrow").classList.toggle("open");
});

// ── Wiring ────────────────────────────────────────────────────────────────────
document.getElementById("addRedirectBtn").addEventListener("click", addRedirect);
document.getElementById("addBulkBtn").addEventListener("click", addBulkRedirects);

document.getElementById("rFromPath").addEventListener("keydown", e => { if (e.key === "Enter") addRedirect(); });
document.getElementById("rToPath").addEventListener("keydown",   e => { if (e.key === "Enter") addRedirect(); });

// ── Helpers ───────────────────────────────────────────────────────────────────
function escHtml(s) {
    return String(s).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");
}

// ── Init ──────────────────────────────────────────────────────────────────────
renderPatterns();
renderOutput();
